name: Frontend CI

on:
  push:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install deps
        run: npm install --prefix frontend
      - name: Build
        run: npm run build --prefix frontend
